### ISSUE TITLE
To-Do: Feed Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#40]
**Front-end:**
- [x] Make profile image larger
- [x] Polish text, buttons. Literally everything
- [ ] Fix feed title, description according to the type (see this issue - https://github.com/abijithanikkuruthi/educollab/issues/51)
- [x] **Low Priority:** Make "customize" an icon with pencil or something

**Back-end:**
- [x] Implement suggestions backend 
      - Display the top 10 of **upvoted** curriculums based on the subject subscriptions of the user
      - Remove the curricula already being followed by the user
