### ISSUE TITLE
To-Do: Explore Index Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#41]
**Front-end:**

- [x] Fix margins for title (and everything else)
- [x] Nice layout for **Fields** boxes
      - **Low Priority:** Make field squares with 40-50% transparent image in background with text.
      - Upon hover, the image should become more transparent or should get a tint and text should be more visible
      -  Boxes could look something like [this](https://www.bluleadz.com/hs-fs/hubfs/Blog_pics/quora-choose-your-interests.png?width=550&name=quora-choose-your-interests.png).

**Back-end:**

- [x] Send no. of curriculum for each subject

**Comment by l8518** [comment]
@ConanKapoor  I improved the explore layout a bit - i think it is enough for mvp
