### ISSUE TITLE
To-Do: Explore Subject Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#42]
**Front-end:**
- [x] Remove search bar and button
- [x] Polish and re-layout everything 
- [x] Better list structure for the curriculua
      - **Low priority:** Maybe also have a button saying "subscribe" right there only. It will be informative to know which curriculua user had already subscribed to even when the user is searching.
- [x] Link curriculum to their respective pages
- [x] Put subject details in a prettier way

**Back-end:**
- [x] Sort curricula for a subject by total counts of upvotes
