### ISSUE TITLE
To-Do: Curriculum Show Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#43]
**Back-end:**
- [x] send details of bits associated with that curriculum
- [x] send if user owns the curriculum
- [x] Comment functionality for curriculum page

**Front-end work dependency on Back-end:**
- [x] Show a list of bits
- [x] Edit curriculum button if you own the curriculum
- [x] Add comments

**Front-end:**
- [x] Polish the buttons and texts
- [x] Re-layout everything
- [x] Requires add bit button for **any user**
