### ISSUE TITLE
To-Do: Curriculum Index (My curricula) Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#44]
**Front-end:**
- [ ] Fix/Add Title for the page
- [ ] Polish texts, button and the table
- [ ] Re-layout everything

**Back-end:**
- [x] Send list of curricula made by the user 
- [x] Send list of curricula subscribed by the user

**Front-end work dependency on Back-end:**
- [ ] Make collapsible list for user made curricula and subscribed curricula
