### ISSUE TITLE
To-Do: New Curriculum Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#45]
**Front-end:**
- [x] Add/Fix Title for the page
- [x] Better filtering of field, subject and topic
- [x] Polish buttons, texts...everything
- [x] Re-layout everything
