### ISSUE TITLE
To-Do: Edit Curriculum Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#46]
**Front-end:**
- [x] Add/Fix Title for the page
- [x] Show a list of bits associated with the curriculum
- [x] Show a placeholder texts if there are no bits for that curriculum
- [x] "Add bit" button needed
- [x] Polish buttons, texts...everything
- [x] Re-layout everything

**Back-end:**
- [x] Send a list of bits for the particular curriculum.

**Comment by l8518** [comment]
Decided on a little bit simpler solution for now that works
