### ISSUE TITLE
To-Do: New Bit Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#47]
**Front-end:**
- [x] Add/Fix Title for the page
- [x] Polish buttons, texts...everything
- [x] Re-layout everything

**Back-end:**
- [x] **Important:** Make functionality of uploading files.

**Comment by abijithanikkuruthi** [comment]
Upload function implemented in  bugfix/mvp_changes branch
