### ISSUE TITLE
To-Do: Show Bit Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#48]
**Front-end:**
- [ ] Change the form to labels (Read-only stuff)
- [ ] Add/Fix Title for the page
- [ ] Polish buttons, texts...everything
- [ ] Re-layout everything

**Back-end:**
- [x] Add "Edit bit" button if the user owns it
- [x] Add Comment functionality

**Front-end work dependency on Back-end:**
- [ ] Prettifying "Edit bit" button
- [ ] Prettifying and laying out comments.
