### ISSUE TITLE
To-Do: Edit Bit Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#49]
**Front-end:**
- [ ] Add/Fix Title for the page
- [ ] Polish buttons, texts...everything
- [ ] Re-layout everything

**Back-end:**
- [x] Check why bit information is being shown in brackets with comma when a file is added (basically as a tuple)

**Comment by little-endian-0x01** [comment]
Don't put commas when updating a db object. Python statements have no commas like any other language. It translates them into tuples.
