### ISSUE TITLE
To-Do: My Profile Page

### ISSUE THREAD

**Issue by little-endian-0x01** [abijithanikkuruthi/educollab#50]
**Front-end:**
- [x] User details has to be polished
- [x] Fix feed title, description according to the type (see this issue - )
- [x] Add edit profile button if the profile is of user
- [x] Add/Fix Title for the page
- [x] Polish buttons, texts...everything
- [x] Re-layout everything

**Comment by abijithanikkuruthi** [comment]
Part of mvp/profile branch

**Comment by l8518** [comment]
done as of now
